### ISSUE TITLE
Minhas Férias aparece 0 ou 1 ao invés de Sim ou Não 

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#1]
Cadastrar Novas Férias(Professor) Informações de antecipação de 13º e próximo salario quando escolhido “Não” aparece resultado 0, quando escolhido “Sim” aparece resultado 1 essa informação só é visível na tela minhas férias.
![erroteste1](https://user-images.githubusercontent.com/25201112/30717867-34f9f0da-9eec-11e7-8de7-a5a503f8f6d9.png)

**Comment by gilmarjoia** [comment]
Corrigido

**Comment by pneduardo1989** [comment]
OK!
