### ISSUE TITLE
Em registrar frequência permite que você cadastre a frequência sem informar o assunto da ocorrência, ao selecionar o código da ocorrência não aparece o campo somente com a descrição da ocorrência, apesar de mostrar o assunto ao selecionar o código, um campo com a descrição da ocorrência se faz necessário ao visualizar os detalhes da ocorrência só é possível saber o código, não é possível ver a descrição da ocorrência. O campo assunto da ocorrência é obrigatório

### ISSUE THREAD

**Issue by sandrobessa** [gilmarjoia/sysicomp#12]

**Comment by JFDValente** [comment]
acrescentei a descrição da ocorrência dentro do 'dropDownlist' que fica na tela de cadastro e de edição da Frequência.

**Comment by LilianeCastro** [comment]
![registrar_frequencia_codigo_ocorrencia](https://user-images.githubusercontent.com/26257882/31324952-d4cf18e6-ac85-11e7-9194-02f5496c6961.png)

Não permite mais o cadastro da frequência sem selecionar o assunto da ocorrência, caso clique em Registrar Frequências aparece uma mensagem no campo que está sem determinada informação, como pode ser observado na imagem acima.

**Comment by LilianeCastro** [comment]
![registrar_frequencia_codigo_ocorrencia_2](https://user-images.githubusercontent.com/26257882/31324979-2a7fc894-ac86-11e7-950c-19e90c8c6652.png)

É assim que os códigos aparecem ao clicar na opção do Código da Ocorrência para cadastro, acreditamos que isso resolve, pois informa o código e uma descrição do mesmo.

![detalhes_frequencia](https://user-images.githubusercontent.com/26257882/31325030-a9447b66-ac86-11e7-8416-fc5d15f49931.png)

Ao visualizar a frequência aparecem os campos cadastrados, logo está atendendo ao que foi solicitado.

**Comment by sandrobessa** [comment]
Reaberto, pois o código continua sendo exibido sem a descricao ao consultar o registro

**Comment by JFDValente** [comment]
ajustei o dropdownlist para exibir a informação no seguinte formato: codigo - assunto, conforme a imagem abaixo:
![image](https://user-images.githubusercontent.com/20117581/31359562-7b66b30c-ad18-11e7-843e-647dc9e7a254.png)
