### ISSUE TITLE
Em cadastrar frequência permite que você cadastre a falta informando o código, assunto de uma ocorrência e período já anteriormente cadastrados gerando duplicidade em banco

### ISSUE THREAD

**Issue by sandrobessa** [gilmarjoia/sysicomp#14]

**Comment by JFDValente** [comment]
Criei um método no model de 'Frequencias', chamado: 'verificarSeDataEhValida', o Controller chama esse método para validar se as datas informadas estão conflitando com alguma data que já foi cadastrada anteriormente, isso foi feito tanto no cadastro quanto na replicação de Frequências.
