### ISSUE TITLE
Em minhas frequências o professor apenas visualiza as ocorrências, não aparece as informações de dias pagos e dias de falta, a tela que deve ser exibida é a mesma de detalhes de frequência e apenas omitir as opções de criar, editar, excluir a frequência cadastrada, é permitido a opção de visualizar detalhes

### ISSUE THREAD

**Issue by sandrobessa** [gilmarjoia/sysicomp#15]

**Comment by LilianeCastro** [comment]
![detalhes_professor](https://user-images.githubusercontent.com/26257882/31324812-8fd78eae-ac84-11e7-9323-9918266d2204.png)

Foram adicionados novos campos ao clicar em Minhas frequências (perfil: Professor). Os novos campos são Código da Ocorrência e Descrição, como mostra a imagem acima. Os ícones que permitiam que o professor pudesse realizar Criar, Editar ou Excluir uma frequência foram removidos.
Notar que antes da tabela temos um resumo, e nele podem ser observados o número de ocorrências e a quantidade de dias a pagar, conforme o exemplo.
