### ISSUE TITLE
Ao clicar em visualizar detalhes de frequências e aparecer as frequências cadastradas, não é possível visualizar os detalhes de cada registro cadastrado, não aparece a opção de visualizar detalhes de frequências cadastradas

### ISSUE THREAD

**Issue by sandrobessa** [gilmarjoia/sysicomp#16]

**Comment by LilianeCastro** [comment]
![detalhes_frequencia](https://user-images.githubusercontent.com/26257882/31324708-84484aac-ac83-11e7-8eca-badc6523268a.png)

Antes tínhamos apenas os campos #, Nome, Data Inicial, Data Final quando clicávamos no ícone de visualizar Detalhes.
Conforme a imagem (perfil: Secretaria), foram adicionados os campos, Código da Ocorrência, Descrição da Ocorrência e três ícones ao lado, caso queira editar a frequência, excluí-la ou replicá-la.

**Comment by LilianeCastro** [comment]
Resolvido.
