### ISSUE TITLE
Erro no Framework registrar frequência

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#17]
ao registrar uma nova frequência, após informar os dados e clicar em registrar frequência aparece uma tela de erro, informando aparentemente um erro no framework.
![whatsapp image 2017-10-10 at 00 43 54](https://user-images.githubusercontent.com/25201112/31394835-53bb33d8-adad-11e7-8287-333797e19562.jpeg)

**Comment by LilianeCastro** [comment]
@pneduardo1989 esse erro ainda persiste ou pode fechar a Issue?
