### ISSUE TITLE
Erro no Framework minhas frequências

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#18]
ao registrar uma nova frequência, após informar os dados e clicar em registrar frequência aparece uma tela de erro, informando aparentemente um erro no framework.
![whatsapp image 2017-10-10 at 00 43 54](https://user-images.githubusercontent.com/25201112/31395001-b31c5208-adad-11e7-8e4b-4467f418f4ff.jpeg)

**Comment by LilianeCastro** [comment]
@pneduardo1989 esse erro ainda persiste ou pode fechar a Issue?
