### ISSUE TITLE
Registrar vários períodos de férias oficiais

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#2]
É possível informar para as férias oficiais, período de férias menor que 45 dias, e registar diversos períodos de férias até completar 45 dias e em cada período informar que quer receber antecipação do 13º e próximo salário.
![erroteste1](https://user-images.githubusercontent.com/25201112/30717934-607b67f2-9eec-11e7-97bb-34d5a63d2a77.png)

**Comment by gilmarjoia** [comment]
Corrigirei esta issue

**Comment by gilmarjoia** [comment]
Irei trocar a busca por primeira adição de adiantamento para primeiro pedido.

**Comment by LilianeCastro** [comment]
@gilmarjoia você fez a troca? A issue já está corrigida?

**Comment by LilianeCastro** [comment]
![issue2](https://user-images.githubusercontent.com/26257882/32967310-87b06c52-cbb3-11e7-8cd8-9c8d6f9a18d7.png)
No primeiro cadastro ele está de fato exigindo que no 3º registro de férias informe a quantidade de dias necessárias para chegar a 30/45 dias. 
Depois que eu cadastro os 3 períodos de férias, eu clico em editar no de 34 dias e coloco menos dias, no caso ficaram 32, ele salva. Não deveria fazer isso.

![issue2](https://user-images.githubusercontent.com/26257882/32966890-b724762e-cbb1-11e7-8fb9-c6584f5c6348.png)

Ele também está permitindo as férias de um ano para o outro. @sandrobessa @pneduardo1989 acredito que não haja problema com relação a isso, preciso de uma posição de vocês.

**Comment by gilmarjoia** [comment]
Verificar a correção da segunda parte da issue 2,

**Comment by LilianeCastro** [comment]
A segunda parte está Ok.
