### ISSUE TITLE
Adiantamento de Férias só pode ser solicitado na 1ª vez que for solicitado o período de férias e desativar o botão para futuras solicitações de férias

### ISSUE THREAD

**Issue by sandrobessa** [gilmarjoia/sysicomp#24]

**Comment by gilmarjoia** [comment]
Já corrigido

**Comment by pneduardo1989** [comment]
ainda não corrigido
![errosissue24](https://user-images.githubusercontent.com/25201112/31636533-d8920d80-b298-11e7-9210-47af0cd71752.png)

**Comment by LilianeCastro** [comment]
@gilmarjoia dá uma olhada nisso e dê uma posição antes de sexta, por favor.

**Comment by pneduardo1989** [comment]
Ao editar um registro de férias, é possivel alterar a antecipação de 50% do 13º salario e antecipação férias, para férias de tipo usufruto
![errosprint3-cadastro de ferias](https://user-images.githubusercontent.com/25201112/31844296-c814600e-b5c5-11e7-9d9c-1c5a4380feaa.png)

**Comment by LilianeCastro** [comment]
@gilmarjoia como anda essa Issue?

**Comment by gilmarjoia** [comment]
Acabei de colocar um correção
