### ISSUE TITLE
Retirar a divisão que existe entre professores e funcionários e colocar todos juntos com o titulo de Solicitações de Férias dos Servidores

### ISSUE THREAD

**Issue by sandrobessa** [gilmarjoia/sysicomp#27]

**Comment by JFDValente** [comment]
modifiquei o método 'Search' do model 'FeriasSearch' para que retornasse todos os funcionarios independente do cargo, e comentei, na view 'ListarTodos', a parte de exibição de separa dos funcionários, bem como modiquei o título para ficar de acordo com o referido no issue: Solicitações de Férias dos Servidores
