### ISSUE TITLE
Férias do tipo usufruto podendo solicitar 13º e prox salário

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#3]
O professor está com a possiblidade de solicitar antecipação do 13º e antecipação do próximo salário em férias do tipo usufruto.
![erroteste1](https://user-images.githubusercontent.com/25201112/30717976-82bd7a62-9eec-11e7-9445-940cbb4b79ea.png)

**Comment by gilmarjoia** [comment]
Corrigido - quando o professor escolher férias do tipo usufruto, a funcionalidade é desabilitada para o check

**Comment by sandrobessa** [comment]
Bug já corrigido porém não fora fechado pelo Gilmar
