### ISSUE TITLE
editar frequência com dados anteriores cadastrados

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#32]
ao editar um registro de frequência ele permite que seja alterado os dados e salvo com dados anteriormente gravados por um outro registro de frequência  gerando duplicidade
![errosprint3-cadastrofrequecia](https://user-images.githubusercontent.com/25201112/31844104-cbdcc79a-b5c4-11e7-94e9-489f4d9ec195.png)

**Comment by gilmarjoia** [comment]
issue #32 corrigida

**Comment by pneduardo1989** [comment]
reaberto
![errosprint3-cadastrofrequecia3](https://user-images.githubusercontent.com/25201112/32139800-594e735e-bc22-11e7-9374-41cd70a2f820.png)

**Comment by JFDValente** [comment]
corrigido a actionUptade, e alterado retorno da rotina pra verificar se a data a ser cadastrada ou modifica é válida, no model de Frequências....

**Comment by pneduardo1989** [comment]
reaberto:
![errosprint3-cadastrofrequecia4](https://user-images.githubusercontent.com/25201112/32147953-e0e89184-bcc5-11e7-8b47-7f5f6824b608.png)

**Comment by gilmarjoia** [comment]
Corrigido, mudança na validação das datas

**Comment by pneduardo1989** [comment]
reaberto, ainda persiste o erro.

**Comment by gilmarjoia** [comment]
Corrigido, quando fiz o comite da validação ele desatualizou  verificação no controller, onde tinha != -1, ficou == 0, por isso era possível cadastrar faltas em períodos iguais. Acho que esse issue pode ser fechado na próxima sprint já @pneduardo1989

**Comment by LilianeCastro** [comment]
Não está repetindo o erro em meus testes, @sandrobessa espero sua posição para fechar esta Issue!
