### ISSUE TITLE
replicar férias durante um mês

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#33]
ao replicar um registro de frequência cadastrado informando a quantidade de dias de um mês ele replica a mesma quantidade de dias para o próximo mês. Ex replicar data 01/01/2017 a 31/01/2017 o replicado irá gerar 01/02/2017 à 03/03/2017
![errosprint3-replicar](https://user-images.githubusercontent.com/25201112/31844142-0dc2a2ba-b5c5-11e7-8c74-531607ed0e8e.png)

**Comment by JFDValente** [comment]
ajustei a rotina para verificar se o registro corresponde a um mês inteiro, se corresponder, ele replica para o próximo mês inteiro, tratei também os casos de o intervalo de data ser em dias que não existem no mês seguinte.
