### ISSUE TITLE
Não é possível editar férias com informações de data que se repetem  

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#34]
Ao editar um registro de férias, não é possivel alterar data, dentro de qualquer intervalo, do registro atual cadastrado(Ex: data registarda no qual cliquei para editar 01-01-2017 à 30-01-2017 se na hora de editar eu informar uma data dentro desse intervalo ele não deixa salvar dando erro de datas já cadastradas)

**Comment by gilmarjoia** [comment]
issue #34 corrigida
