### ISSUE TITLE
Registrar vários períodos de férias de usufruto iguais   

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#35]
Ao cadastrar um registro de férias do tipo usufruto, é possivel informar data dentro do intervalo de outras férias do tipo usufruto já cadastradas anterior mente causando duplicidade.
![errosprint3-cadastro de ferias](https://user-images.githubusercontent.com/25201112/31844340-05168e64-b5c6-11e7-9850-a5da402fb40a.png)

**Comment by gilmarjoia** [comment]
Issue #35 corrigida

**Comment by pneduardo1989** [comment]
permanece o erro: Ao cadastrar um registro de férias do tipo usufruto, é possivel informar data dentro do intervalo de outras férias do tipo usufruto já cadastradas anterior mente causando duplicidade.
![errosprint3-cadastro de ferias2](https://user-images.githubusercontent.com/25201112/32118089-7fc3674c-bb1e-11e7-967a-53cd5aca1f7f.png)

**Comment by gilmarjoia** [comment]
Foi corrigido
