### ISSUE TITLE
cadastro de frequência entre um data já anteriormente informada

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#36]
ao cadastrar uma ocorrencia ele permite que seja informado um intervalo de  período no qual haja algum data já anteriormente cadastrado. Ex: já existe falta no dia 10, caso eu informe uma nova falta do dia 9 ao dia 11 ele ´permite que seja cadastrado 
![errosprint3-cadastrofrequecia2](https://user-images.githubusercontent.com/25201112/32118440-b7bc6a44-bb1f-11e7-9ebc-142f1e93cf47.png)

**Comment by JFDValente** [comment]
ajustei a rotina que verifica se a data de cadastro é válida, no model de Frequências, incluindo estas situações em que uma data já cadastrada está dentro do intervalo especificado, e incluindo também datas que são interseções em intervalos já cadastrados.
