### ISSUE TITLE
solicitação de 50% do 13º e antecipação férias

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#37]
Não é possivel solicitar adiantamento de 50% do 13º e Antecipação de Férias no cadastro do primeiro período de férias.

**Comment by LilianeCastro** [comment]
Como está o status dessa Issue, eu consegui solicitar os adiantamentos no 1o cadastro e não permitiu nos posteriores.

![cadastroferias](https://user-images.githubusercontent.com/26257882/32140316-98f258ac-bc33-11e7-9392-21af490a4774.png)

**Comment by pneduardo1989** [comment]
corrigido
