### ISSUE TITLE
editar férias aviso que professor não pode alterar pois ultrapassou 30 dias

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#38]
A secretária  informa os 45 dias de férias oficiais ao professor;
Ao tentar fazer uma edição nos períodos já informados, não é possível informar uma nova data (respeitando o limite de 45 dias), pois o sistema dá o aviso que o professor já ultrapassou os 30 dias. 
![errosprint3-editarferias](https://user-images.githubusercontent.com/25201112/32119692-0677975e-bb24-11e7-8aa5-d77c1239d0de.png)

**Comment by gilmarjoia** [comment]
Corrigido, o problema era o select, estava pegando o id do próprio usuário e não do servidor
