### ISSUE TITLE
editar informações de frequência com a mesma data 

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#39]
ao editar um registro de frequência ele não permite que seja alterado o cod da ocorrência e permaneca com a mesma data de falta, informando que já existe uma ocorrência já cadastrada para essa data.
![errosprint3-editarfrequencia](https://user-images.githubusercontent.com/25201112/32120279-01398f16-bb26-11e7-89f2-5cb927b2d173.png)

**Comment by gilmarjoia** [comment]
@pneduardo1989  to tentando achar esse erro aqui mas não aparece, eu consigo editar somente a ocorrencia e não da erro\

**Comment by pneduardo1989** [comment]
issue fechada
