### ISSUE TITLE
cadastro de frequência,descrição errada do cod cadasrado

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#40]
o cadastrar uma falta e informar os dados, ao salvar ele aparece o cod correto cadastrado, mas a descrição é a prox cadastrada no banco, ex: cadastrei uma falta com cod 66, mas a descrição que aparece depois de salva é do cod 67.
![errosprint3-cadastrofrequecia3](https://user-images.githubusercontent.com/25201112/32139847-87ac7fa6-bc23-11e7-8add-0da1ae8dac67.png)

**Comment by LilianeCastro** [comment]
@JFDValente pode cuidar dessa?
![ocorrencia2](https://user-images.githubusercontent.com/26257882/32140297-6186d59c-bc32-11e7-9f8f-5d17ffa07c73.png)

**Comment by JFDValente** [comment]
corrigida a rotina que que mostrava o assunto da ocorrência na tela de "minhas frequências" e detalhar Frequências"

![image](https://user-images.githubusercontent.com/20117581/32147270-ff0e4222-bcba-11e7-867f-c10791dcfc11.png)
