### ISSUE TITLE
editar férias do tipo usufruto

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#41]
Ao editar um registro de férias, é possivel alterar a antecipação de 50% do 13º salario e antecipação férias, para férias de tipo usufruto
![errosprint3-editarferias2](https://user-images.githubusercontent.com/25201112/32139943-843b4944-bc26-11e7-9be1-ff23a7763bc4.png)

**Comment by gilmarjoia** [comment]
Com a correção da #24 esta issue foi corrigida
