### ISSUE TITLE
Relatório de férias

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#42]
Relatório de Férias, não está ordenado em ordem alfabética e está sendo exibido as férias do tipo usufruto cadastradas, são apenas férias do tipo oficial

**Comment by LilianeCastro** [comment]
@VitorTaichou olha essa.

**Comment by VitorTaichou** [comment]
Procurando resolver

**Comment by VitorTaichou** [comment]
Resolvido o/
