### ISSUE TITLE
cadastro de férias, solicitar benefícios na segunda solicitação em diante 

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#43]
É possivel solicitar adiantamento de 50% do 13º e Antecipação de Férias no cadastro do segundo período de férias em diante. Só é permitido solicitar essas opções apenas no primeiro.
![errosprint3-cadastro de ferias3](https://user-images.githubusercontent.com/25201112/32148167-1be1f43a-bcc9-11e7-90df-bab85bda6450.png)

**Comment by LilianeCastro** [comment]
Esperando seu teste para fecharmos a Issue, @sandrobessa
