### ISSUE TITLE
editar férias, alterar benefícios de férias oficiais 

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#44]
Ao editar um registro de férias, é possível alterar a antecipação de 50% do 13º salario e antecipação férias, para férias de tipo oficial, causando assim várias solicitações oficiais todas solicitando os benefícios
![errosprint3-cadastro de ferias4](https://user-images.githubusercontent.com/25201112/32149607-813540f8-bcdd-11e7-9472-40dc4fa67ddd.png)

**Comment by LilianeCastro** [comment]
Fiz os testes e passou e apenas na primeira solicitação ele poderia modificar para oficial. Exclui a primeira solicitação e fiz outra. Ele passou a considerar como primeira solicitação a antiga, anterior da nova que eu havia cadastrado, e permitiu que eu modificasse, mas a nova não permitiu o adiantamento @sandrobessa aguardo os teus testes para fechar a Issue.
