### ISSUE TITLE
Ao registrar as férias o sistema está permitindo modificar de Oficial para Usufruto todas as férias, não tendo obrigatoriedade de ter férias Oficiais. 

### ISSUE THREAD

**Issue by LilianeCastro** [gilmarjoia/sysicomp#45]
![ferias](https://user-images.githubusercontent.com/26257882/32677792-3898c02e-c636-11e7-99f6-03eaf7c307e5.jpeg)

Na hora q ele mudar de oficial para usufruto, se já existir solicitação de adiantamento de décimo e/ou adiantamento férias, eles devem ser desativados.

**Comment by JFDValente** [comment]
as chaves de adiantamento nos forms não funcionam se o tipo for férias de usufruto, e também não funcionando se já houverem registros de férias com adiantamento.

**Comment by LilianeCastro** [comment]
![issue](https://user-images.githubusercontent.com/26257882/32778934-3019a876-c912-11e7-8055-dfae9e960647.png)

Ainda persiste.
Isso só acontece com o primeira cadastro válido, ele você pode modificar para usufruto, oficiais, 13º, férias. Se tu excluir o 1º cadastro válido, o segundo na lista se torna o cadastro que tu pode fazer tudo. 
Replica estes passos:
Perfil secretaria > Gerenciar Ferias > Controlar Ferias > Prof Alberto.
Se tiver qualquer coisa cadastrada, tu remove.

Registra as férias:
Tipo: Usufruto. 
Data Inicio e Final: 01/11 - 10/11.
Ok.

Faz um novo registro.
Tipo: Oficial. 
Data Inicio e Final: 11/11 - 15/11
Adiantamento de férias e decimo: Sim.
Ok.

![1](https://user-images.githubusercontent.com/26257882/32779282-80e48126-c913-11e7-98c2-1031e5cf9cdf.png)

Vai estar de acordo com a imagem acima. 
Então tu vai até as férias de 01/11 - 10/11 que tu cadastrou primeiro e muda o tipo para Usufruto.
E salva.
O resultado vai ser igual o da figura abaixo.
![2](https://user-images.githubusercontent.com/26257882/32779375-e532ede8-c913-11e7-8e22-a9d95568f850.png)

Quando tu diz que ele é usufruto, então ele tem que desativar os adiantamentos. Mas ele está permitindo que fiquem ativos.



Então está acontecendo só com o primeiro cadastro, tanto que se tu apagar ele, o segundo vai agir conforme o que tu excluiu. Se tu cadastrar outra coisa, vai repetir o erro.

**Comment by LilianeCastro** [comment]
Resolvido.

**Comment by VitorTaichou** [comment]
![image](https://user-images.githubusercontent.com/18365471/32782238-2ea1975e-c91e-11e7-89f1-2a58600194ea.png)

Constatado que não é mais possível registrar adiantamentos em férias do tipo USUFRUTO, mesmo criando uma solicitação de Férias do tipo OFICIAL, marcando os adiantamentos, depois editando e trocando pra USUFRUTO.
