### ISSUE TITLE
Possível solicitar férias diferentes em períodos iguais 

### ISSUE THREAD

**Issue by pneduardo1989** [gilmarjoia/sysicomp#5]
Professor e TAD pode solicitar registro de férias diferentes sendo que são nos mesmo períodos e do mesmo tipo.
![erroteste2](https://user-images.githubusercontent.com/25201112/30765566-4fb38bd4-9fbe-11e7-958b-7028dfe81bf8.png)

**Comment by gilmarjoia** [comment]
Pegarei esta issue

**Comment by gilmarjoia** [comment]
Resolvido: O usuário pode cadastrar férias de usufruto no mesmo período de férias oficiais, mas não pode cadastrar usufruto em períodos iguais. O mesmo vale para férias oficiais
